// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://loncayexjrjewmmgxdci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvbmNheWV4anJqZXdtbWd4ZGNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2OTUwNzIsImV4cCI6MjA3MTI3MTA3Mn0.U98XwephBTR3pRCAI56OThwe2LcBys-Y16eC6Cyov8c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});